//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Booking_Detail = new HashSet<Booking_Detail>();
        }
    
        public int Booking_ID { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<System.TimeSpan> Booking_Time { get; set; }
        public Nullable<long> Customer_Phone { get; set; }
        public Nullable<int> Trip_ID { get; set; }
        public Nullable<int> Train_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Detail> Booking_Detail { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Train Train { get; set; }
    }
}
