//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Detail
    {
        public int Booking_ID { get; set; }
        public int Seat_No { get; set; }
        public int Coach_ID { get; set; }
        public Nullable<decimal> Booking_Price { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
