//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayBooking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayBookingEntities : DbContext
    {
        public RailwayBookingEntities()
            : base("name=RailwayBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Booking_Detail> Booking_Detail { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Coach_Type> Coach_Type { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Seat_Type> Seat_Type { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Station_Details> Station_Details { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<Trip_Price> Trip_Price { get; set; }
    }
}
