//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Train_ID { get; set; }
        public int Coach_ID { get; set; }
        public int Seat_No { get; set; }
        public int Seat_Type_ID { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
