//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Train_ID { get; set; }
        public int Trip_ID { get; set; }
        public Nullable<System.DateTime> Trip_Date { get; set; }
        public string Trip_Start_Location { get; set; }
        public string Trip_End_Location { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
